### ISSUE TITLE
msix package not available for download on Github

### ISSUE THREAD

**Issue by red-erik** [MicrosoftDocs/PowerShell-Docs#5543] opened 2020-03-06 11:58 UTC
msix package not available for download on Github

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell on Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment] 2020-03-06 14:18
This is a duplicate of #5519 - The MSIX package is coming soon.

**Closed by sdwheeler** 2020-03-06 14:18 UTC
Labels: Status-Duplicate
