### ISSUE TITLE
Fix using variable for nested ForEach-Object -Parallel calls

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#7266] opened 2021-02-18 14:33 UTC
# Summary of the new document or enhancement

- List of articles that need to be updated:
  - https://docs.microsoft.com/powershell/module/microsoft.powershell.core/foreach-object
  - https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_foreach
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: https://github.com/PowerShell/PowerShell/pull/14548
- Link(s) to related issue(s) in the PowerShell/PowerShell repo:

## Description of what changed

Fix using variable for nested ForEach-Object -Parallel calls. Need to document current behavior in previous versions.

**Comment by chasewilson** [comment] 2021-02-18 15:41
duplicate of [#5436](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5436)

**Closed by chasewilson** 2021-02-18 15:41 UTC
Labels: core, parallelism
