### ISSUE TITLE
Where's -OutBuffer Parameters

### ISSUE THREAD

**Issue by jschadow** [MicrosoftDocs/PowerShell-Docs#4949] opened 2019-10-17 16:32 UTC
Don't go all Linux now... there's lots missing in documentation now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b27fb99c-9218-34c5-9952-65bee8c91b66
* Version Independent ID: f8c29ce4-92d3-1ce6-90c2-13e01ab5228f
* Content: [Invoke-RestMethod (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6#inputs)
* Content Source: [reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment] 2019-10-17 20:48
`Invoke-RestMethod` does not have a `-OutBuffer` parameter. What exactly are you looking for?

**Comment by mklement0** [comment] 2019-10-19 20:02
@jschadow:

`-OutBuffer` is a _common parameter_, not specific to `Invoke-RestMethod`; from the [linked topic](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md#commonparameters), emphasis added:

> This cmdlet supports the common parameters: `-Debug`, `-ErrorAction`, `-ErrorVariable`, `-InformationAction`, `-InformationVariable`, `-OutVariable`, **`-OutBuffer`**, `-PipelineVariable`, `-Verbose`, `-WarningAction`, and `-WarningVariable`. For more information, see [about_CommonParameters](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_CommonParameters.md).

**Comment by sdwheeler** [comment] 2020-03-20 16:16
Duplicate of #4484

**Closed by sdwheeler** 2020-03-20 16:16 UTC
Labels: Area-HelpSystem, Area-OPS-Issue
