### ISSUE TITLE
Got here through the wrong command (Register ArgementCompleter).

### ISSUE THREAD

**Issue by TheGhost2804** [MicrosoftDocs/PowerShell-Docs#4704] opened 2019-08-29 12:15 UTC
When running: help "Register-ArgumentCompleter -Online" from powershell it launches this page, that is incorrect.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: ccb49a78-f4da-a117-5414-ffdc89dac124
* Version Independent ID: ea319662-5062-e3e3-bdfa-244e8a405778
* Content: [Receive-PSSession (Microsoft.PowerShell.Core)](https://docs.microsoft.com/nl-nl/powershell/module/Microsoft.PowerShell.Core/Receive-PSSession?view=powershell-5.0)
* Content Source: [reference/5.0/Microsoft.PowerShell.Core/Receive-PSSession.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/Receive-PSSession.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment] 2020-03-20 16:05
Duplicate of #2998

**Closed by sdwheeler** 2020-03-20 16:05 UTC
Labels: Area-HelpSystem, Status-Duplicate
