### ISSUE TITLE
winget Install Version 7.3.2 is not found

### ISSUE THREAD

**Issue by PStoner3** [MicrosoftDocs/PowerShell-Docs#9794] opened 2023-02-03 19:20 UTC
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3

### Summary

Powershell version 7.3.2 is not the default version. Version 7.3.1 is the one found

### Details

The screenshot showing the output of `winget search Microsoft.PowerShell` shows the version as 7.3.2.0. However, when I run the same command I'm shown version 7.3.1.0
![powershell_731](https://user-images.githubusercontent.com/17929362/216688214-f7cbc1da-9b13-4572-8e43-26b8b8f2b392.png)

If I try to install using the version number 7.3.2.0 as in the screenshot I receive `No version found matching 7.3.2.0`
![powershell_732](https://user-images.githubusercontent.com/17929362/216688642-93d51687-6054-4026-a84a-62d3d9181917.png)

And Powershell itself shows a new version is available
![powershell_nv](https://user-images.githubusercontent.com/17929362/216688864-d9b6e706-7a6c-4b80-8afb-341510d7192a.png)

### Suggested Fix

Ensure the correct install package is in place for winget to find it or revert the documentation to display version 7.3.1.0

**Comment by sdwheeler** [comment] 2023-02-03 21:06
Duplicate of #9781

**Closed by sdwheeler** 2023-02-03 21:06 UTC
Labels: resolution-duplicate, resolution-wont-fix, area-setup, issue-doc-bug

**Comment by PStoner3** [comment] 2023-02-07 17:47
Apologies, but I would like to inquire how this can be closed when winget still shows last version of 7.3.1.0
![winget_powershell_2023_02_07](https://user-images.githubusercontent.com/17929362/217324160-5651ba0b-58c1-4ab9-a62f-d461c7ba4c9c.png)

**Comment by sdwheeler** [comment] 2023-02-08 16:19
@PStoner3 This is fixed now.
