### ISSUE TITLE
Document the automatic `$EnabledExperimentalFeatures`  variable

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/PowerShell-Docs#9722] opened 2023-01-18 21:48 UTC
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Automatic_Variables

### Summary

The automatic  `$EnabledExperimentalFeatures` variable lists all currently enabled experimental features.

Not sure in what version it was introduced, but it is present as of at least 7.3.1

**Comment by sdwheeler** [comment] 2023-01-18 23:30
This is a duplicate of #9720 and was fixed in #9721.

**Closed by sdwheeler** 2023-01-18 23:30 UTC
Labels: doc-bug, needs-triage

**Comment by mklement0** [comment] 2023-01-18 23:39
Good to know, @sdwheeler, but, for future reference:

A nondescript title such as "Add missing automatic variables" coupled with not mentioning the _specific names_ of those missing variables even in the body of the issue makes it all but impossible to detect such duplicates.

**Comment by sdwheeler** [comment] 2023-01-19 00:04
@mklement0 yeah, this was a quickie fix. I didn't expect anyone to need to find it.
