### ISSUE TITLE
Note re MSIX should be removed

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/PowerShell-Docs#6122] opened 2020-06-14 11:01 UTC
You can remove the Note:
The MSIX package has not been released yet. When released, the package will be available in the Microsoft Store and from the GitHub releases page.

They are on the Github https://github.com/PowerShell/PowerShell/releases

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell on Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7#install-as-a-net-global-tool)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment] 2020-06-14 15:38
Duplicate of #5519

**Closed by sdwheeler** 2020-06-14 15:38 UTC
Labels: duplicate, setup

**Comment by sdwheeler** [comment] 2020-06-14 15:46
The MSIX is still not published to the store. We are waiting for that.
