### ISSUE TITLE
PowerShell Documentation - Get-ChildItem “Common Parameters”

### ISSUE THREAD

**Issue by aksarben** [MicrosoftDocs/PowerShell-Docs#10074] opened 2023-05-13 18:28 UTC
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.3

### Summary

The syntax samples show <CommonParameters> as an optional parameter. But I can’t find an explanation of what “Common Parameters” are. 

Am I missing something?

**Comment by sdwheeler** [comment] 2023-05-15 15:15
Duplicate of #4484

**Closed by sdwheeler** 2023-05-15 15:15 UTC
Labels: resolution-duplicate, issue-doc-bug
