### ISSUE TITLE
Describe what happens if you try to remove a file that is locked

### ISSUE THREAD

**Issue by deadlydog** [MicrosoftDocs/PowerShell-Docs#6900] opened 2020-11-14 23:16 UTC
It would be helpful if the documentation described what happens when you try to remove an item (e.g. a file) that it locked by another process. Does it throw an exception causing the script to halt? Just do a Write-Error and continue? It would be helpful if that was listed so users didn't have to try and replicate a locked file to do trial and error to find out how the cmdlet reacts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d99989c4-80af-52f2-3c19-b7d1defa03ed
* Version Independent ID: 0b18157a-a191-4733-90db-7dfceda2c99f
* Content: [Remove-Item (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-6&source=docs)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Remove-Item.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Remove-Item.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment] 2020-11-15 00:42
Duplicate of #6797 - This is being tracked in PowerShell/PowerShell#13882.

**Closed by sdwheeler** 2020-11-15 00:42 UTC
