### ISSUE TITLE
Adding Ubuntu 22.04 to Powershell for linux documentation

### ISSUE THREAD

**Issue by JaldeaR** [MicrosoftDocs/PowerShell-Docs#8794] opened 2022-05-06 14:06 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

7.2

### Link to affected document

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2#ubuntu

### Description of the documentation error

Regarding the category Ubuntu,

The documentation for this section is missing ubuntu 22.04 overview, i saw its been already added within the microsoft documents for installation purposes but this documentation isn't up to date on that yet.

 

### Suggested fix

The following should be added to the Ubuntu section of the page.
"
Support for Powershell on ubuntu 22.04

https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
"

The current installation guide can be used with the above link instead of the previous versions.

**Comment by sdwheeler** [comment] 2022-05-06 14:23
We are working on this already.

Duplicate of #8786

**Closed by sdwheeler** 2022-05-06 14:23 UTC
Labels: setup, doc-bug
