### ISSUE TITLE
Documentation does not match behaviour for Copy-Item

### ISSUE THREAD

**Issue by ilsaloving** [MicrosoftDocs/PowerShell-Docs#10760] opened 2024-01-02 21:31 UTC
### Type of issue

Missing information

### Feedback

I am trying to use Copy-Item to recursively copy a source directory's contents to a new destination, as per Example 2.  It does _not_ work.  Instead, it copies the contents of the first _subfolder_ it finds inside the source folder.  
eg: I have the following `$Path="\\share\source"`
\\share\source\a\1.txt
\\share\source\a\2.txt
\\share\source\b\3.txt
\\share\source\c.txt

If I do `Copy-Item "$Path\*" -Destination $installPath -Recurse -Force`

The destination folder contains:
1.txt
2.txt

I don't know if the documentation is wrong, or if Copy-Item is just horribly broken.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/copy-item?view=powershell-5.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md

### Author

@sdwheeler

### Document Id

1eace7de-83aa-39a7-7a19-862e9e37b5f7

**Comment by sdwheeler** [comment] 2024-01-02 21:39
There are strange and unexpected behaviors with using wildcard paths with recursion. 
- See the discussion in Issue #10640. 

We are working on updates to the documentation but it's hard to describe adequately.

Closing as duplicate of #10640

**Closed by sdwheeler** 2024-01-02 21:39 UTC
Labels: needs-triage
