### ISSUE TITLE
Add UseOSCIndicator setting to enable progress indicator in terminal

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#7372] opened 2021-03-22 21:08 UTC
# Summary of the new document or enhancement

- List of articles that need to be updated: https://docs.microsoft.com/powershell/scripting/learn/experimental-features
- New articles that need to be created:
- Link(s) to related code PR(s) in the PowerShell/PowerShell repo: PowerShell/PowerShell#14927
- Link(s) to related issue(s) in the PowerShell/PowerShell repo:

## Description of what changed

Add new `$PSStyle.Progress.UseOSCIndicator` setting to use conemu's OSC indicator to show progress in the terminal window, which is also supported by Windows Terminal. Since this is a custom OSC that isn't widely supported, it defaults to `$false`. Since this is an advanced setting not supported by many terminals, had to give it a technical name. iTerm2, for example, uses `ESC]9;` as a notification OSC sequence so you get a pop-up dialog instead of progress.

**Comment by chasewilson** [comment] 2021-03-25 17:48
I think this is a duplicate of [this issue](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7304)

Closing for now but if I'm wrong, feel free to reopen

**Closed by chasewilson** 2021-03-25 17:48 UTC
Labels: experimental

**Comment by sdwheeler** [comment] 2021-03-25 18:00
@chasewilson Doh!
