### ISSUE TITLE
CommonParameters documentation not displayed in cmdlet reference

### ISSUE THREAD

**Issue by pchatelle** [MicrosoftDocs/PowerShell-Docs#4484] opened 2019-06-26 13:26 UTC
please expand on what " [&lt;CommonParameters&gt;]" means or are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e67ee59-8a3e-59ad-7c8d-a78605f55b66
* Version Independent ID: 3c8b8ee9-6a97-4eda-d184-49e728abf0a6
* Content: [Compress-Archive (Microsoft.PowerShell.Archive)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @anmenaga
* Microsoft Alias: **anmenaga**

**Comment by sdwheeler** [comment] 2019-06-27 15:03
See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_commonparameters.

There is actually text and a link to this in the source of the article but there is a bug in the code that builds the website to prevents that paragraph from being rendered.

**Comment by pchatelle** [comment] 2019-06-27 17:24
Sean!


You are the first person to respond to a comment in a day or two!


I found the info, but you deserve a big thank you!


Pat.


________________________________

**Comment by HughDevlin** [comment] 2020-09-14 13:22
Please update this issue with progress. Thank you.

**Comment by HughDevlin** [comment] 2020-09-14 13:24
Please provide a link to the common parameters page, on each reference page where the common parameters are cited.

**Comment by sdwheeler** [comment] 2020-09-14 15:13
@HughDevlin The link in is the source documentation already. The problem is in our rendering engine. We are working on a fix for this.

**Comment by HughDevlin** [comment] 2020-09-14 15:31
The failing component was identified in June 2019.

**Comment by batamig** [comment] 2021-06-28 05:34
Hi all - FYI this is happening too in all the md files in https://github.com/Azure/azure-docs-powershell-aip/tree/master/Azure%20Information%20Protection/AzureInformationProtection

See for example: https://docs.microsoft.com/en-us/powershell/module/azureinformationprotection/add-aipscannerrepository?view=azureipps#parameters

It's really strange to me bc this is straight up markdown, no reference links or yaml files. 
Is there any sort of workaround until this is fixed?

Thanks!!

**Comment by sdwheeler** [comment] 2021-06-28 12:47
The OPS build converts the markdown to YAML before rendering the HTML site. The bug is in the YAML conversion. The fix for this will probably not be ready until the end of the year.

**Comment by HughDevlin** [comment] 2021-06-28 18:40
which year? in the above the failing component was identified in June 2019

**Comment by sdwheeler** [comment] 2021-06-28 21:23
@HughDevlin this year, 2021. The problem predates 2019. That is just when this issue was created. Getting the problem fixed has been a resource issue. We have a Dev working on this right now. Fixing the component is not hard. Integrating the updated component into the publishing pipeline is the more difficult problem. But we do have people working on this. So the end is in sight.

**Comment by sdwheeler** [comment] 2022-07-07 20:11
This is being tracked in https://github.com/PowerShell/platyPS/issues/540

**Closed by sdwheeler** 2022-07-07 20:11 UTC
Labels: helpsystem, ops-issue
