### ISSUE TITLE
some HelpUris aren't redirecting properly

### ISSUE THREAD

**Issue by corbob** [MicrosoftDocs/PowerShell-Docs#5125] opened 2019-11-19 06:17 UTC
# Documentation Issue
A number of the Microsoft HelpUris aren't redirecting properly.

## Context of the issue

- URL to the article (Docs or GitHub URL):
- Issue affects the following content (check all that apply): (Haven't tested in 7, but 5.1 and 6 share the HelpUris so presumably it's there too)
  
  **Cmdlet reference & about_ topics**
  - [ ] Version 7 content
  - [x] Version 6 content
  - [x] Version 5.1 content

## Detailed description of the issue

Quick and dirty script used to generate list:

```powershell
Get-Command * -CommandType Cmdlet,Function | ? helpuri -like '*microsoft.com*' | select name,helpuri,@{'n'='redirectUri';'e'={(iwr $_.helpuri -method head).BaseResponse.RequestMessage.RequestUri.AbsoluteUri}} | ? redirectUri -like 'https://www.microsoft.com*'
```

Table of the HelpUris I've been able to identify (will edit to add suggested redirects as I find them):

| Name | HelpUri | RedirectedUri | Suggested redirect |
|-----|-----|-----|-----|
|Clear-Host|https://go.microsoft.com/fwlink/?LinkID=225747|https://www.microsoft.com/en-ca/?ref=go| https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/functions/clear-host |
|prompt|https://go.microsoft.com/fwlink/?LinkID=225750|https://www.microsoft.com/en-ca/?ref=go|
|Debug-Runspace|https://go.microsoft.com/fwlink/?LinkId=403731|https://www.microsoft.com/en-ca/?ref=go| https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/debug-runspace|
|Disable-ExperimentalFeature|https://go.microsoft.com/fwlink/?LinkID=2046963|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/disable-experimentalfeature|
|Disable-RunspaceDebug|https://go.microsoft.com/fwlink/?LinkId=403733|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/disable-runspacedebug|
|Enable-ExperimentalFeature|https://go.microsoft.com/fwlink/?LinkID=2046964|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/enable-experimentalfeature|
|Enable-RunspaceDebug|https://go.microsoft.com/fwlink/?LinkId=403732|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/enable-runspacedebug|
|Format-Hex|https://go.microsoft.com/fwlink/?LinkId=526919|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/format-hex|
|Get-CmsMessage|https://go.microsoft.com/fwlink/?LinkID=394370|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-cmsmessage|
|Get-ComputerInfo|https://go.microsoft.com/fwlink/?LinkId=799466|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-computerinfo|
|Get-FileHash|https://go.microsoft.com/fwlink/?LinkId=517145|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-filehash|
|Get-PSHostProcessInfo|https://go.microsoft.com/fwlink/?LinkId=517012|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-pshostprocessinfo|
|Get-PSSessionCapability|https://go.microsoft.com/fwlink/?LinkId=623709|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-pssessioncapability|
|Get-Runspace|https://go.microsoft.com/fwlink/?LinkID=403730|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-runspace|
|Get-RunspaceDebug|https://go.microsoft.com/fwlink/?LinkId=403734|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-runspacedebug
|Get-Uptime|https://go.microsoft.com/fwlink/?linkid=834862|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-uptime|
|Get-Verb|https://go.microsoft.com/fwlink/?LinkID=160712|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/functions/get-verb|
|Import-PowerShellDataFile|https://go.microsoft.com/fwlink/?LinkID=623621|https://www.microsoft.com/en-ca/?ref=go| https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/import-powershelldatafile |
|New-FileCatalog|https://go.microsoft.com/fwlink/?LinkId=786749|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/new-filecatalog|
|New-Guid|https://go.microsoft.com/fwlink/?LinkId=526920|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-guid|
|New-PSRoleCapabilityFile|https://go.microsoft.com/fwlink/?LinkId=623708|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-psrolecapabilityfile|
|Protect-CmsMessage|https://go.microsoft.com/fwlink/?LinkId=394373|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/protect-cmsmessage|
|Register-ArgumentCompleter|https://go.microsoft.com/fwlink/?LinkId=528576|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter|
|Set-TimeZone|https://go.microsoft.com/fwlink/?LinkId=799469|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-timezone|
|Test-FileCatalog|https://go.microsoft.com/fwlink/?LinkId=786750|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/test-filecatalog|
|Test-PSSessionConfigurationFile|https://go.microsoft.com/fwlink/?LinkID=217039|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/test-pssessionconfigurationfile|
|Unprotect-CmsMessage|https://go.microsoft.com/fwlink/?LinkId=394374|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/unprotect-cmsmessage|
|Wait-Debugger|https://go.microsoft.com/fwlink/?LinkId=403735|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/wait-debugger|
|Write-Information|https://go.microsoft.com/fwlink/?LinkId=525909|https://www.microsoft.com/en-ca/?ref=go|https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-information|

**Comment by sdwheeler** [comment] 2019-11-19 16:49
@corbob Thanks for reporting this. This is a known issue and we have already fixed this for the most part.. For PowerShell v6 you can run `Update-Help -Force` and that will download the latest help with new HelpUris. We have also updated the HelpURIs for PowerShell v5.1, but we haven't been able to publish updated help CABs for some time. I wrote a blog post about this: https://devblogs.microsoft.com/powershell/updating-help-for-older-versions-of-powershell/. In that post I provide instructions on how to build the updated help CABs for PowerShell 5.1 from the docs source files on GitHub.

There are two difficulties to overcome with respect to HelpURIs.
1. There HelpUris are compiled into the code, but the targets of those links have not been maintained over the years. The URIs were reused from version to version, when they should have been unique. And the URIs don't always point to the correct target path or version do to changes in the publishing system.
2. Update-Help can download full help content with updated HelpURIs. But PowerShell does not install the help by default. So the initial URIs (built into the code) may not be accurate. And, due to technical, process, and "legal" reasons, we haven't been able to publish updated help CABs for PowerShell 5.1 and older.

**Comment by sdwheeler** [comment] 2020-03-20 16:17
Duplicate of #2998

**Closed by sdwheeler** 2020-03-20 16:17 UTC
Labels: Area-HelpSystem
