### ISSUE TITLE
Docs needed for 'Parsing of compound command-line tokens into arguments is surprising'

### ISSUE THREAD

**Issue by joeyaiello** [MicrosoftDocs/PowerShell-Docs#3038] opened 2018-10-15 21:38 UTC
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/issues/6467

**Comment by joeyaiello** [comment] 2018-10-31 20:44
Changes should go into about_Parsing, per the discussion in the linked issue

**Comment by sdwheeler** [comment] 2020-04-10 17:27
Closing as duplicate of #3440. That issue has more information.

**Closed by sdwheeler** 2020-04-10 17:27 UTC
Labels: Area-Engine, Area-Language, Pri-2, Status-Duplicate
