### ISSUE TITLE
Exceptions thrown not documented

### ISSUE THREAD

**Issue by albertvaka** [MicrosoftDocs/PowerShell-Docs#7379] opened 2021-03-25 13:33 UTC
# Documentation Issue

The docs for cmdlets don't mention if they can throw exceptions (and which ones if they do) or if they will never throw. As a developer, I want to know if I need to handle exceptions when calling things like [`Stop-Server`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/stop-service?view=powershell-7.1) but it's not documented whether such cmdlets can or cannot throw.

## Context of the issue

- URL to the article (Docs or GitHub URL): Eg: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/stop-service?view=powershell-7.1)
- Issue affects the following content (check all that apply): All cmdlet docs.
- Is the issue specific to a platform (Y/N - Win/macOS/Linux): No.

**Comment by sdwheeler** [comment] 2021-03-25 15:50
Duplicate of #6797

Unfortunately this is not an easy problem to solve. A lot of cmdlets do not define exceptions. The exceptions that occur come from lower level .NET APIs. But for cmdlets that do define exceptions we don't have a good way to discover those for documentation. 

We created a feature request to make documenting exceptions more scalable. See https://github.com/PowerShell/PowerShell/issues/13882. The discussion and issue is being tracked there.

**Closed by sdwheeler** 2021-03-25 15:50 UTC
Labels: question, shiproom
