### ISSUE TITLE
## Update

### ISSUE THREAD

**Issue by briandjohansen1** [MicrosoftDocs/PowerShell-Docs#9341] opened 2022-10-22 16:18 UTC
## Update

I started doing a more thorough investigation and talked a bit with @markekraus about the implementation and it turns out I had managed to narrowly thread the needle in my initial investigation for cases where there isn't any encoding behaviors. There's actually several that need to be documented:

- How **Body** handles:

  1. [x] **IDictionary** on non-GET calls
  1. [x] **FormObject**
  1. [x] **XmlNode**
  1. [x] **Stream**
  1. [x] **byte[]**

- [x] Clarify that **ContentType** changes the encoding if specified.

I'll work to address this, but it will likely take longer than I initially hoped.

_Originally posted by @michaeltlombardi in https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9312#issuecomment-1284606727_

**Comment by michaeltlombardi** [comment] 2022-10-24 13:46
This appears to be a duplicate of the information already captured (and tracked) in #9312. Closing it for now.

**Closed by michaeltlombardi** 2022-10-24 13:46 UTC
