### ISSUE TITLE
libssl1.1 is not longer supported on alpine in favor of openssl 3

### ISSUE THREAD

**Issue by pregress** [MicrosoftDocs/PowerShell-Docs#10817] opened 2024-01-23 13:39 UTC
### Type of issue

Outdated article

### Feedback

Newer alpine versions don't support libssl1.1 anymore.
[alpine issue tracker](https://gitlab.alpinelinux.org/alpine/aports/-/issues/15575)

> fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz 
> fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
>   ERROR: unable to select packages:
>     libssl1.1 (no such package):
>      required by: world[libssl1.1]

### Page URL

https://learn.microsoft.com/en-us/powershell/scripting/install/install-alpine?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/install-alpine.md

### Author

@sdwheeler

### Document Id

da6c7c79-75ee-f19a-09b5-59dc21139242

**Comment by sdwheeler** [comment] 2024-01-23 14:34
We don't support Alpine 3.19 yet.
Duplicate of #10775

**Closed by sdwheeler** 2024-01-23 14:34 UTC
Labels: needs-triage
