### ISSUE TITLE
WHY?!

### ISSUE THREAD

**Issue by kernelpickle** [MicrosoftDocs/PowerShell-Docs#5359] opened 2020-01-25 17:42 UTC
Why does this page (or ANY of the other online man pages) even need to exist?!  The Get-Help command SHOULD already have everything I need to know to use the command properly, but even after running "Update-Help -Force" (even running as admin) I'm STILL getting errors for  several modules, and the modules that were updated don't even contain as much info as this site!

If your developers would just remove their heads from the obvious location we ALL know they're located, boot up a real Terminal in a Unix based system, and RTFM!  If they did, they'd see how a manual is supposed to look--there are some man pages, that actually span multiple pages!  There is ABSOLUTELY no reason that you couldn't have ALL of this information right inside of PowerShell, and I can understand not wanting to store a ton of local copies of things--but when I use the Get-Help &lt;Command&gt; -Online parameter, it should NEVER take me out of the terminal and shove a browser in my face!  If I'm going to use a browser, I'm going to read someone's blog article on how to use the command I'm looking up, because I'm SURE to get more detailed info and better examples than I would find here.

My point is simply that the experience of using PowerShell is so awful, that given the choice of using it in an ideal environment (on a modern system with a full GUI) OR using a Bash terminal (on an ancient system without a GUI, and a partially busted keyboard) while sitting on a pile of hot garbage--I'll need to know exactly which keys aren't working before I make my decision!

On top of that, there are other simple things I SHOULD be able to do without ever leaving the terminal, like EDIT A TEXT FILE!  SERIOUSLY?!  It's 2020 for crying out loud, and PowerShell isn't some ancient legacy system that's included for backwards compatibility!  It's actively being updated and is new enough that there are still systems I support (yup, but that's manufacturing for ya!) that don't even have it installed, because it wasn't built into Windows until after XP!  Hell, there are PLENTY of things I still use cmd for, because it's easier to use and still does a better job for some things than PowerShell does!

...and ANOTHER thing!  While I'm on the topic of cmd vs PowerShell, why is it that I absolutely CANNOT expect my scripts to actually WORK if I don't launch them from a batch file first?!  Why isn't there even an option to right-click &gt; Run as Admin for these stupid things?!  Microsoft allegedly built PowerShell for more in depth Sys Admin work than batch files were capable of, but I still can't live without that ancient mess!  FIX THIS MESS because I need REAL TOOLS to do my job in a Windows environment, and I simply cannot be reliant on third-party tools to do the simplest of things that PowerShell struggles with (can I get a Sudo command, please?!) because I can't expect to have them installed on EVERY system I need to manage, and the built-in tools need to function!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f902191e-e620-89a2-8d31-37756a202be3
* Version Independent ID: 4532edd3-5890-2ab7-a7eb-d366d0462d7e
* Content: [Update-Help (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/Update-Help?view=powershell-7&viewFallbackFrom=powershell-5.0)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/Update-Help.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/Update-Help.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by doctordns** [comment] 2020-01-26 14:22
So 2 things:
1. Update-Help was an excellent solution to an older problem with Windows PowerShell. Errors in help, at that time, were almost impossible to get fixed 'quickly' due to the release mechanisms in place for Windows PowerShell. By moving this out of Windows and allowing you to update help at ANY time, this problem is minimised.  This IS a good thing, especially when combined with the open-sourcing of PowerShell help material. I have updated a LOT of the documentation. Once - in a course, we found an error. In class, I demonstrated fixing and submitting the fix. In a few days, we could download that help. What more do you want in terms of responsiveness?

2. There are some challenges with Update-Help nevertheless. Some help files do not have all non-EN-US versions (an issue for me in En-GB land). Not ALL modules are created by the same team so there are variations, sadly, in how help is dealt with.  And some (badly written) modules do not have the necessary metadata needed to support Update-Help in the first place.  Usually, the error messages) from Update-Help tell you what the issue is. Rather than saying help sucks (which it doesn't) why not file specific issues to get the underlying issues resolved? At the end of the day, your issue is not actionable and feels like just a rant.

Re Editing a text file - this is simple: from PowerShell just type CODE FILENAME. and up comes the file in VS Code. Or use Notepad. PowerShell itself is not a file editor. But VS Code and Notepad are. I recommend using the right tools for the job.

Re: running a PowerShell script - you do so in PowerShell. You do NOT need to open Cmd.exe first. 

Finally,  Having used PowerShell for getting on 16+ years, I'd argue that PowerShell IS the tool you want. You just need to learn how it works and how to work with it.

**Closed** 2020-01-27 16:58 UTC

**Comment by jsilverm** [comment] 2020-05-15 19:46
What you said...I did think it was a bad experience when in Windows PowerShell 5.1, new users following along with a book or online tutorials would be confronted with a whole bunch of errors running Update-Help the first time (or any time for that matter).  My single favorite beginner book includes as the first exercise in Chapter 3: "Run Update-Help and ensure that it completes without errors..." -- years later I've still never seen that happen without explicitly repressing them...

I hope that when I see the numerous things obviously still wrong with individual help files I will either point them out or eventually directly contribute changes myself if I am sure enough.  The first couple of examples of the first (I was sure what was there was wrong but not quite certain what it should be) have already been updated.  Here's to lighting candles...

**Comment by jsilverm** [comment] 2020-05-15 19:50
To clarify, both the current content of the latest help files, which is ever-improving, and the system itself are much nicer than when I first tried to use PowerShell.  Even today the 5.1 docs for countless cmdlets explicitly tell you that wildcards are permitted in notes for certain parameters, but the "Wildcards Permitted: False" directly contradicts that -- that definitely confused me the first few days of working with 5.1 back then.  Thanks Doc, for improving the health of the docs.
