### ISSUE TITLE
libssl1.1 is not longer included in alpine 3.19

### ISSUE THREAD

**Issue by davidkoenig-shiftavenue** [MicrosoftDocs/PowerShell-Docs#10958] opened 2024-03-18 09:55 UTC
### Type of issue

Code doesn't work

### Feedback

To use alpine you have to use the libraray libssl3 instead of libssl1.1. Its already corrected in the .NET documentation: https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine

### Page URL

https://learn.microsoft.com/de-de/powershell/scripting/install/install-alpine?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/install/install-alpine.md

### Author

@sdwheeler

### Document Id

da6c7c79-75ee-f19a-09b5-59dc21139242

**Comment by sdwheeler** [comment] 2024-03-18 18:42
We don't support Alpine 3.19 yet.
Duplicate of #10817

**Closed by sdwheeler** 2024-03-18 18:42 UTC
Labels: needs-triage
