### ISSUE TITLE
Online help for Install-Module from PSCore links to WinPS

### ISSUE THREAD

**Issue by travis-c-lagrone** [MicrosoftDocs/PowerShell-Docs#4416] opened 2019-06-08 01:34 UTC
Issue Details
-----------------

**When:**

```powershell
Microsoft.PowerShell.Core\Get-Help -Name 'PowerShellGet\Install-Module' -Online
```

**Expect:**

https://docs.microsoft.com/en-us/powershell/module/PowershellGet/Install-Module?view=powershell-6

**Actual:**

https://docs.microsoft.com/en-us/powershell/module/PowershellGet/Install-Module?view=powershell-5.1

**Environment:**

```
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.17763 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.2.1}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Reason(s) for not selecting all version of documents
----------------------------------------------------
Don't have access to all versions of PowerShell with which to test.

**Comment by sdwheeler** [comment] 2020-03-20 16:08
Duplicate of #2998

**Closed by sdwheeler** 2020-03-20 16:08 UTC
Labels: Area-HelpSystem
