### ISSUE TITLE
common beginner error

### ISSUE THREAD

**Issue by awooga** [MicrosoftDocs/PowerShell-Docs#5707] opened 2020-04-03 16:30 UTC
make hello.ps1 - run - "Could not find the task "build" ? open launch.json - ? 

how to get past this please ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919fe42a-edb9-c950-1405-ae723bb6a48e
* Version Independent ID: 781d1d43-834f-7e39-cc60-8905d5803f9b
* Content: [Using Visual Studio Code for PowerShell Development - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-7#feedback)
* Content Source: [reference/docs-conceptual/components/vscode/using-vscode.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/components/vscode/using-vscode.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment] 2020-04-03 16:42
I don't understand the problem you are reporting. Can you provide more context? What are you trying to do? What steps did you do leading up to this problem?

**Comment by awooga** [comment] 2020-04-03 16:47
Hi sean,

I followed the page with installing powershell extension in vsc - then we told to put text into josn file - which file is that per chance ?
Nothing says what file- how you get to this file- only millions of files on my pc - so hard to narrow down where to put the json code ?

😉

sorry being pedantic - but if you follow the page you get lost - it assumes you know vsc and now where to put json code... we dont all know this.

hope this helps. Later in page it says what files json goes in - but is that same earlier..

I hat to assume - as makes ass out of "u" and "me" ?

awooga

________________________________

**Comment by sdwheeler** [comment] 2020-04-05 19:11
Duplicate of #5706

**Closed by sdwheeler** 2020-04-05 19:11 UTC
Labels: Area-VSCode
