### ISSUE TITLE
Get-Package -Scope parameter not working as expected

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/PowerShell-Docs#7148] opened 2021-01-19 22:00 UTC
Hello,
I'm trying to fetch an installed package.
If I use ```Get-Package *PackageName*``` package is returned! SUCCESS

If I use ```Get-Package -Scope CurrentUser *PackageName*``` no results
If I use ```Get-Package -Scope AllUsers *PackageName*``` no results

If I use ```Get-Package -Scope:$null *PackageName*``` error, not supported value
If I use ```Get-Package -Scope:"" *PackageName*``` error, not supported value

So... There seems to be a 3rd state for the scope that isn't null or blank.

The use case is, I'm trying to uninstall a program using intune, that was not installed by intune. Created a powershell script to fetch package and run the uninstall command via start-process. intune running as system didn't find the package, so I tried changing the scope, and it still didn't find the package.

I then tried to run the script under the user scope (in intune) and it still didn't work! That's when I realized the scope is a lie, hehe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3755d90-721e-e9f7-41b3-2063234d0f28
* Version Independent ID: 51100c02-3f5f-98a9-6ba2-62049da4671e
* Content: [Get-Package (PackageManagement) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/get-package?view=powershell-7.1)
* Content Source: [reference/7.1/PackageManagement/Get-Package.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/PackageManagement/Get-Package.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by jonwbstr** [comment] 2021-01-19 22:03
Version info
```
PS C:\Users\JonWebster> get-command get-package|select name,version,source|fl

Name    : Get-Package
Version : 1.0.0.1
Source  : PackageManagement
```

**Comment by chasewilson** [comment] 2021-01-19 23:20
Hey @jonwbstr is is possible for you to update to a newer version of pacakge management? That one is really old and I'm not sure I can really tell you if that's a current bug? or expected behavior.

**Comment by jonwbstr** [comment] 2021-01-19 23:26
That is a really interesting question. I tried to update-module PackageManagement and that failed. Not exactly sure how to update this module. The documentation in that department is being hard to find. Still looking though!

**Comment by chasewilson** [comment] 2021-01-19 23:34
That version is shipped with windows and Isn't installed the same way I believe if you install the latest version of PowerShellGet, it will automatically be installed with it.

**Comment by jonwbstr** [comment] 2021-01-19 23:56
```Install-Module PowerShellGet -Force``` did the trick. Sadly the machines I am managing will be using the version shipped with windows so that's a different problem. As it turns out, 1.4.7 has the same issue.

```
PS C:\WINDOWS\system32> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.4.7      PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...

PS C:\WINDOWS\system32> get-package *goto*

Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
GoTo Opener                    1.0.539                                           msi
GoToMeeting 10.15.0.19228      10.15.0.19228                                     Programs

PS C:\WINDOWS\system32> get-package *goto* -Scope allusers
get-package : No package found for '*goto*'.
At line:1 char:1
+ get-package *goto* -Scope allusers
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...lets.GetPackage:GetPackage) [Get-Package], Exception
    + FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackage

PS C:\WINDOWS\system32> get-package *goto* -Scope currentuser
get-package : No package found for '*goto*'.
At line:1 char:1
+ get-package *goto* -Scope currentuser
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...lets.GetPackage:GetPackage) [Get-Package], Exception
    + FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackage

PS C:\WINDOWS\system32> get-package *goto* -Scope:$null
Get-Package : Cannot validate argument on parameter 'Scope'. The argument is null, empty, or an element of the
argument collection contains a null value. Supply a collection that does not contain any null values and then try the
command again.
At line:1 char:27
+ get-package *goto* -Scope:$null
+                           ~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Package], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPacka
   ge

PS C:\WINDOWS\system32> get-package *goto* -Scope:""
Get-Package : Cannot validate argument on parameter 'Scope'. The argument "" does not belong to the set
"CurrentUser,AllUsers" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the
command again.
At line:1 char:27
+ get-package *goto* -Scope:""
+                           ~~
    + CategoryInfo          : InvalidData: (:) [Get-Package], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPacka
   ge
```

**Comment by jonwbstr** [comment] 2021-01-19 23:58
And in case you're wondering, yes, same result when I use an explicit package name.

**Comment by chasewilson** [comment] 2021-01-20 00:33
We can't repro the behavior and it should work so it seems to be a bug. You can file an [issue here](https://github.com/PowerShell/PowerShellGetv2/issues). I'll be closing this for now but still monitoring for any changes we might need to make for documentation.

**Closed by chasewilson** 2021-01-20 00:33 UTC
Labels: packagemanagement
