### ISSUE TITLE
Add example of specifying provider for `Test-Path -IsValid`

### ISSUE THREAD

**Issue by SteveL-MSFT** [MicrosoftDocs/PowerShell-Docs#10967] opened 2024-03-20 16:54 UTC
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-path?view=powershell-7.4
https://github.com/PowerShell/PowerShell/issues/20847#issuecomment-2010046701

### Summary

Users may be surprised that `test-path -isvalid z:\abc.txt` returns false if `z:` doesn't exist.  

### Details

This is because the cmdlet can't find a provider to perform the validation. 

### Suggested Fix

Add an example to explicitly specify the provider:

test-path -isvalid filesystem::z:\abc.txt

**Comment by sdwheeler** [comment] 2024-03-20 19:43
Duplicate of #10963

**Closed by sdwheeler** 2024-03-20 19:43 UTC
Labels: resolution-duplicate, issue-doc-bug
