### ISSUE TITLE
Using Enums as Function Parameters

### ISSUE THREAD

**Issue by aksarben** [MicrosoftDocs/PowerShell-Docs#10133] opened 2023-06-05 16:19 UTC
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."

### PowerShell Version

7.3

### Summary

Was looking for how to declare function parameters to be enums, and how to pass enum parameters to functions.

### Details

I'm new to enums, and getting an error message in Visual Studio Code that it doesn't recognize an enum I created when I pass it to function.

### Proposed Content Type

About Topic

### Proposed Title

Enum Function Parameters

### Related Articles

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_enum?view=powershell-7.3

**Comment by michaeltlombardi** [comment] 2023-06-05 17:40
I'm not sure I understand how this is different from #10127, which you also filed. Can you elaborate for me?

**Comment by sdwheeler** [comment] 2023-06-05 20:26
Duplicate of #10127

**Closed by sdwheeler** 2023-06-05 20:26 UTC
Labels: issue-doc-idea, needs-triage

**Comment by michaeltlombardi** [comment] 2023-06-05 20:28
@aksarben I think we addressed this in #10135:

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/7e7053e1e160658022b5a4fd5f2a3dbe7fa62a16/reference/7.3/Microsoft.PowerShell.Core/About/about_Enum.md?plain=1#L253-L313

**Comment by aksarben** [comment] 2023-06-05 21:39
Interesting. This page seems to answer the question. Strangely, none of my Google searches returned it.

Thanks for your help (and patience with a newbie!)
