### ISSUE TITLE
Missing link to the latest version of the PS in the Russian translation

### ISSUE THREAD

**Issue by andreich1980** [MicrosoftDocs/PowerShell-Docs#7790] opened 2021-07-10 05:53 UTC
In the Russian translation there's a missing link https://aka.ms/powershell-release?tag=stable

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Установка PowerShell в Windows - PowerShell](https://docs.microsoft.com/ru-ru/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/powerShell-Docs.ru-ru/blob/live/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by chasewilson** [comment] 2021-07-12 14:37
Thank you for the feedback. 

This is a duplicate of [this issue](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7786). We're working internally to address the problem as it spans multiple translated issues. 

I'll be closing this issue for now and if you have any more feebck, feel free to post it in the linked issue.

**Closed by chasewilson** 2021-07-12 14:37 UTC
