### ISSUE TITLE
Add note that Get-Service is Windows-only cmdlet

### ISSUE THREAD

**Issue by peetrike** [MicrosoftDocs/PowerShell-Docs#6631] opened 2020-09-16 06:12 UTC
PowerShell 6+ doesn't have `Get-Service` in non-Windows releases, but this is not mentioned in help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f066f0-a853-8a3a-fd53-269b52d8263a
* Version Independent ID: 52b4131a-0ccb-3942-1b13-7b57faf329d5
* Content: [Get-Service (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Get-Service?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Management/Get-Service.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Get-Service.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by sdwheeler** [comment] 2020-09-16 12:38
This is documented in https://docs.microsoft.com/powershell/scripting/whats-new/cmdlet-version. We are working on a way to represent platform compatibility information in the individual cmdlet documents.

**Comment by sdwheeler** [comment] 2020-10-20 20:08
Duplicate of #3632

**Closed by sdwheeler** 2020-10-20 20:08 UTC
Labels: duplicate, helpsystem
