### ISSUE TITLE
Swedish translation is mangled 

### ISSUE THREAD

**Issue by Kleptoflax** [MicrosoftDocs/PowerShell-Docs#8444] opened 2021-12-22 13:17 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1, 7.0, 7.1, 7.2

### Link to affected document

https://docs.microsoft.com/sv-se/powershell/module/microsoft.powershell.core/about/about_try_catch_finally?view=powershell-7.2

### Description of the documentation error

Current wording of the first paragraph in the Syntax section is:
"En try -instruktion innehåller try ett block, noll eller flera block och noll catch eller ett finally block. En try -instruktion måste ha minst ett catch block eller ett finally block."

As I'm writing this and glancing at the "Long description", I realize that that section also has multiple similar issues, where the "special" words (with colorized background) get passed forward in the sentence to what I suppose is just beyond the current (semantic) parse tree branch?

So - the automatic translation service does not seem to treat the special words correctly.

### Suggested fix

An intelligible (and correct, relative to the English wording) wording of the first paragraph in the Syntax section is: 
"En try-instruktion innehåller ett try-block, noll eller flera catch-block och noll eller ett finally-block. En try-instruktion måste ha minst ett catch-block eller ett finally-block."

**Comment by sdwheeler** [comment] 2022-01-04 21:28
Thanks for the report. 
Duplicate of #7951

**Closed by sdwheeler** 2022-01-04 21:28 UTC
Labels: localization, doc-bug
