### ISSUE TITLE
Missing reference to relavent documentation

### ISSUE THREAD

**Issue by TimNFL** [MicrosoftDocs/PowerShell-Docs#5812] opened 2020-04-21 11:44 UTC
the documentation states 

> Beginning in PowerShell 6, the default views for objects are defined in PowerShell source code.

but no other mentions or examples seem to exist for how to define default views in powershell source code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce7319e-0b83-dae5-6f52-290e5ff56604
* Version Independent ID: e363027f-b76b-edbb-22dc-02d5924cfcb9
* Content: [about_Format.ps1xml - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment] 2020-04-21 14:35
Duplicate of #2341

**Closed by sdwheeler** 2020-04-21 14:35 UTC
Labels: Status-Duplicate
