### ISSUE TITLE
the default encoding is unicode (out-file in PS 5.1)

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#4179] opened 2019-04-19 20:05 UTC
The default encoding for out-file in powershell 5.1 is unicode, even when appending to a non-unicode file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 017303b6-1ba6-c1ff-4afb-ff17089c2d47
* Version Independent ID: 6ca0aa0a-2b48-273f-cd95-831d08bef772
* Content: [Out-File (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Utility/Out-File.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Out-File.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment] 2019-04-19 20:35
Duplicate of #4155

**Closed by sdwheeler** 2019-04-19 20:35 UTC
Labels: Area-Cmdlets-Utility, Duplicate
