### ISSUE TITLE
Exclude parameter issue

### ISSUE THREAD

**Issue by brbish** [MicrosoftDocs/PowerShell-Docs#7579] opened 2021-05-13 20:32 UTC
[Enter feedback here]
1. The -Exclude parameter appears to only operate on basically the file at the end of the path (not sure if this is called the leaf, branch, node or maybe something else entirely) not on anything else in the path. If this is incorrect I would like to see an example which works.
2. Also it isn't specified in the documentation whether the -Include or the -Exclude parameter wins when they match the same target. It would be good to know this.

Thanks,

Brent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd63f6e7-f3f3-edbc-acf6-b52de6c0eab4
* Version Independent ID: ffa98c5b-6e0a-dc99-94b2-2fddc3f78da4
* Content: [Get-ChildItem (Microsoft.PowerShell.Management) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by chasewilson** [comment] 2021-05-13 21:02
Hey @brbish, thanks for your feedback here. 

1. I'm not positive what you are meaning in your question here. If you are referenceing that exlude only works on the children files and folders in the path you provide, then yes that's all that it works on. `Get-ChildItem` gets the children items of the parent folder which is the path you provide. It doesn't searth every item in every folder of the path you specify. 

2. It seems to work as you would expect. The the `Include` parameter values are respected and the `exclude` parameters. If you do something like this:  `Get-ChildItem -Path C:\test\* -Include *.txt -Exclude *.txt` : nothing is returned

If you run something like this

```powershell
New-Item C:\Test\Include.txt -Force
New-Item C:\Test\Exclude.txt -Force

Get-ChildItem -Path C:\Test\* -Include *.txt -Exclude *Exclude*
```

You will only get the Include.txt returned. 

I'm going to close this for now but if you have more feedback, I'll be monitoring and can reopen if necessary. 

Thanks!

**Comment by brbish** [comment] 2021-05-13 21:28
Chase, thanks for the quick reply. Some good info there especially the part that indicates exclude overrides include. That is important to know.

However this is what I was trying to ask about. The documentation says this about the exclude parameter:
Specifies, as a string array, a property or property that this cmdlet excludes from the operation. The value of this parameter qualifies the Path parameter.

What I am asking about is that Exclude does not appear to operate against the entire value of the path for any found item. It only appears to operate on the last segment/node (whatever you want to call it, but the item after the last \ in the path) of the path. It never matches anything further up in the path. So to me it seems that saying it "qualifies the Path parameter" is the wrong thing here. I would say the last node / segment / object (whatever is the correct terminology) is what is operates against or qualifies.

**Comment by chasewilson** [comment] 2021-05-14 15:26
Ok, so I've submitted [a PR](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/7583) to clarify the wording a bit and to point out the behavior between **Include** and **Exclude**. 

The `Get-ChildItem` command is still intended to get the child items of the path you specify. It will not traverse up the path you provide. Feel free to provide feedback in the linked pr and I hope this does clarify the expected behavior. 😄

**Closed** 2021-05-14 15:25 UTC
Labels: management

**Comment by brbish** [comment] 2021-05-14 17:17
Just to clarify, I was not clear in that I am only talking about matching (with the Exclude parameter) against the parts of the paths which are enumerated during the recursion by Get-ChildItem; not any part of the path which might exist above the start folder given in the -Path parameter. Hope this is clear. If not let me know.

**Comment by chasewilson** [comment] 2021-05-14 19:20
Ahh that's a misunderstanding on my part.

No, there isn't a way to stop children from being returned by `Get-ChildItem` as a whole by defining a folder. if you exclude a folder name, it won't return the folder itself but still return all children of folders when using `Recurse`.  If you want to filter folder contents out you will have to use further right filtering with Where-Object or something else. 

I hope this helps

**Comment by 20-EverGreen-2** [comment] 2022-01-14 20:38
I have same problems with -Exclude. Examples:

```
PS G:\> Get-ChildItem -LiteralPath "G:\" -Exclude "System Volume Information" -Hidden


    Directorio: G:\


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-rhs-        08/12/2021      7:28                boot
d-rhs-        08/12/2021      7:28                EFI
d-rhs-        27/09/2020     23:36                GRUB
d-rhs-        26/11/2015      3:25                I386
d-rhs-        14/01/2022     11:28                IMG
d--hs-        01/12/2010      8:23                System Volume Information  <<--- WTF??? I filtered above
-a-hs-        31/03/2020     14:16             48 BOOTDISK.KEY
-arhs-        30/10/2015     16:19         400228 bootmgr
-arhs-        30/10/2015     16:19        1147736 bootmgr.efi
-arhs-        31/03/2009     22:20         217769 grldr
-arhs-        31/03/2009     22:20           9216 grldr.mbr
-a-hs-        31/03/2020     14:16            164 _bootDisk.ini
```

```
PS G:\> Get-ChildItem -Path "G:\*" -Exclude "System Volume Information" -Hidden


    Directorio: G:\boot


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a-hs-        03/04/2020     12:09          65536 bcd.LOG
-a-hs-        04/08/2016     21:15              0 bcd.LOG1
-a-hs-        04/08/2016     21:15              0 bcd.LOG2


    Directorio: G:\


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a-hs-        31/03/2020     14:16             48 BOOTDISK.KEY
-arhs-        30/10/2015     16:19         400228 bootmgr
-arhs-        30/10/2015     16:19        1147736 bootmgr.efi
-arhs-        31/03/2009     22:20         217769 grldr
-arhs-        31/03/2009     22:20           9216 grldr.mbr
-a-hs-        31/03/2020     14:16            164 _bootDisk.ini
```

^--- MISSING A LOT OF DIRECTORIES

```
PS G:\> Get-ChildItem -Path "G:\*" -Hidden


    Directorio: G:\


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-rhs-        08/12/2021      7:28                boot
d-rhs-        08/12/2021      7:28                EFI
d-rhs-        27/09/2020     23:36                GRUB
d-rhs-        26/11/2015      3:25                I386
d-rhs-        14/01/2022     11:28                IMG
d--hs-        01/12/2010      8:23                System Volume Information
-a-hs-        31/03/2020     14:16             48 BOOTDISK.KEY
-arhs-        30/10/2015     16:19         400228 bootmgr
-arhs-        30/10/2015     16:19        1147736 bootmgr.efi
-arhs-        31/03/2009     22:20         217769 grldr
-arhs-        31/03/2009     22:20           9216 grldr.mbr
-a-hs-        31/03/2020     14:16            164 _bootDisk.ini
```

Very similar command without -Exclude get all directories. 


I think this cmdlet needs more test of developers this cmdlet is very BUGGY!!!
