### ISSUE TITLE
Document change in assembly loading behaviour

### ISSUE THREAD

**Issue by vexx32** [MicrosoftDocs/PowerShell-Docs#4249] opened 2019-05-01 19:54 UTC
See https://github.com/PowerShell/PowerShell/issues/9488#issuecomment-488342590

Assembly loading behaviour was changed in PowerShell 6.2. Any assemblies listed in `FileList` of a module manifest will be loaded, although this will fail for native assemblies and prevent them being loaded properly later.

As such, native assemblies should always be excluded from the FileList entries in a module manifest.

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [X] Impacts 6 document (6.2)
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment] 2019-06-26 20:40
Update about_Modules and release notes.

**Comment by sdwheeler** [comment] 2019-11-18 21:44
@SteveL-MSFT We need a more complete description that we can add to the appropriate docs. Also, is there plans to address any of this in PSv7?

**Comment by sdwheeler** [comment] 2019-11-22 03:23
@vexx32 Is this something you could help us document?

**Comment by vexx32** [comment] 2019-11-22 03:52
:grin: I can do my best, but I'm fairly sure there'll be parts I don't know well enough. I'm not really sure why the behaviour was changed to begin with, among other things.

Perhaps @daxian-dbw or @PaulHigin might be more familiar with the rationale and the changes themselves.

If they aren't able to help out here for whatever reason I'm sure I can chat to a few other folx who know the background info better and help y'all put something together as best I can! 😊

**Comment by sdwheeler** [comment] 2019-12-12 17:51
@daxian-dbw Can you help with core information?

**Comment by joeyaiello** [comment] 2019-12-12 17:53
Subsequently, we need to also document https://github.com/PowerShell/PowerShell/pull/11032 as native DLL resolution has also changed.

**Comment by daxian-dbw** [comment] 2020-01-10 22:56
I'm curious about this one. The comment https://github.com/PowerShell/PowerShell/issues/9488#issuecomment-488342590 sounds to me a regression in our code. Are we now treating that regression by design now?

**Comment by vexx32** [comment] 2020-01-11 04:17
@daxian-dbw I am unsure. @adityapatwardhan's comment seems to indicate that was the case, but I don't recall anyone else saying either way.

**Comment by SteveL-MSFT** [comment] 2020-01-14 15:21
Seems that if we had caught that side effect in 6.2, we should have fixed it.  But now the question is if anyone is dependent on that change in behavior.  Since the behavior is additive (in that as far as I know, you would get an error prior to 6.2 if FileList contained native binaries?) it seems the lesser evil is to keep the new behavior and document than breaking it.

**Comment by vexx32** [comment] 2020-01-14 19:09
Aye. Combined with the work @iSazonov did to enable module authors to tweak the native binary search paths, it's overall more usable.

It is still a bit annoying that DLLs in `FileList` are being automatically loaded to be honest; this behaviour doesn't really exist for any other files that I'm aware of. We can't, for example, define a module just with manifest and a collection of files that contain functions -- a psm1 is still required there. 😕

**Comment by iSazonov** [comment] 2020-01-15 04:02
> Seems that if we had caught that side effect in 6.2, we should have fixed it. 

Have we a tracking issue?

**Comment by joeyaiello** [comment] 2020-01-22 21:24
The question we haven't answered is whether this has been fixed in 7.0. 

Is this still the behavior?

**Comment by adityapatwardhan** [comment] 2020-05-27 21:14
I can confirm that the behavior for `7.0.1` is to load the managed assemblies in the file list.

**Comment by sdwheeler** [comment] 2020-05-27 21:59
@adityapatwardhan What I need is a full description of the load behavior so that I can update the docs to reflect the new behavior.

**Comment by adityapatwardhan** [comment] 2020-05-28 00:25
I have opened a new issue: https://github.com/PowerShell/PowerShell/issues/12821

That issue needs committee review. If the issue is going to be fixed, then we do not need to change the docs, if issue is not fixed we need to update the docs.

Update would be something like, probably a note.

[!NOTE] All the DLL files listed in FileList property of the module manifest will be attempted to load. If a native DLL is in the file list, it will fail to load in the process and the error is ignored. All managed DLLs will be loaded in the process.

**Comment by adityapatwardhan** [comment] 2020-06-16 01:14
PR opened to change the behavior back to not loaded assemblies listed in `FileList` https://github.com/PowerShell/PowerShell/pull/12968

**Comment by adityapatwardhan** [comment] 2020-08-25 15:39
Here is the assembly load behavior by version:

### 6.2.x -- Soon to be EOL 

We introduced a regression from 6.1.0 where we started loading everything listed in FileList property of the module manifest. 

### 7.0.x -- LTS

The regression was not fixed here. 

The suggested text for 6.2.x and 7.0.x is:

[!NOTE] All the DLL files listed in FileList property of the module manifest will be attempted to load. If a native DLL is in the file list, it will fail to load in the process and the error is ignored. All managed DLLs will be loaded in the process.

### 7.1.0.preview.5 + 

The regression was fixed and we do not load assemblies listed in the FileList property. https://github.com/PowerShell/PowerShell/pull/12968

@daxian-dbw @SteveL-MSFT - So the current state is we have no regression between 6.1.0 -> 7.1.0. But there is a change in behavior betweem 7.0.0 -> 7.1.0. 

Should we consider https://github.com/PowerShell/PowerShell/pull/12968 for back porting to 7.0.x?

**Comment by adityapatwardhan** [comment] 2020-08-25 15:50
@sdwheeler @chasewilson Do you have sufficient information for the doc update?

**Closed** 2020-11-02 15:30 UTC
Labels: language
