### ISSUE TITLE
Provide explanation for 4 variations of Invoke-RestMethod 

### ISSUE THREAD

**Issue by MNF** [MicrosoftDocs/PowerShell-Docs#6637] opened 2020-09-16 23:46 UTC
At the beginning of the article there are 4 syntax variations without any explanation. It will be good to add a description for each of them before corresponding snippet. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65ac7780-af59-1176-1c0a-ec821902c2f8
* Version Independent ID: f8c29ce4-92d3-1ce6-90c2-13e01ab5228f
* Content: [Invoke-RestMethod (Microsoft.PowerShell.Utility) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @JamesWTruher
* Microsoft Alias: **jimtru**

**Comment by sdwheeler** [comment] 2020-09-17 13:59
@MNF This is a known issue that we are working on fixing. The markdown source for the cmdlet reference contains the Parameter Set name for each set but that information is not getting rendered on the webpage. We are a couple of months away from a solution.

**Comment by doctordns** [comment] 2020-12-18 17:43
The joys of an ever evolving documentation platform!
IN the mean time, would it help to add 4 examples to demonstrate each of the variations?

**Comment by sdwheeler** [comment] 2021-06-08 21:10
Duplicate of #2422

**Closed by sdwheeler** 2021-06-08 21:10 UTC
Labels: duplicate, helpsystem
