### ISSUE TITLE
Encoding parameter accept numeric Ids and name of registered code pages

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#2937] opened 2018-09-19 07:11 UTC
Issue Details
-----------------

PR https://github.com/PowerShell/PowerShell/pull/7636  enhance the encoding transformation attribute:
- to allow numeric Ids of registered code pages (like -Encoding 1251)
- to allow string names of registered code pages (like -Encoding "windows-1251")

Affected cmdlets:
```powershell
gcm -ParameterName Encoding

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-Content                                        6.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Export-Clixml                                      6.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Export-Csv                                         6.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Export-PSSession                                   6.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Format-Hex                                         6.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Get-Content                                        6.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Import-Csv                                         6.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Out-File                                           6.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Select-String                                      6.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Send-MailMessage                                   6.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Set-Content                                        6.1.0.0    Microsoft.PowerShell.Management
```

Full list supported code pages we can found in
https://github.com/dotnet/corefx/blob/master/src/System.Text.Encoding.CodePages/src/System/Text/EncodingTable.Data.cs

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment] 2018-10-26 13:56
This is a duplicate of or related to the following issues:

- #3027
- #2000

**Comment by iSazonov** [comment] 2018-10-26 17:51
It is new functionality. It is not dup but related mentioned issues.

**Comment by joeyaiello** [comment] 2019-04-17 20:19
We should document this by adding a line or two to the parameter description of each cmdlet and/or about_Encoding to say that this parameter accepts codepage values. about_Encoding should link to [the .NET documentation on [Encoding.CodePage](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.codepage?view=netcore-2.2)

**Closed** 2019-04-20 15:16 UTC
Labels: Area-Cmdlets-Core, Pri-Medium
