### ISSUE TITLE
Link to common parameters

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/PowerShell-Docs#6613] opened 2020-09-11 15:24 UTC
[Enter feedback here]

Please provide a link to this page, on each reference page where the common parameters are cited.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 307b69cd-d651-db61-3ab0-6a357105c791
* Version Independent ID: f83b7011-1b36-45aa-93ff-e1b03536378d
* Content: [about_CommonParameters - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7)
* Content Source: [reference/7.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment] 2020-09-14 12:10
Duplicate of #4484

**Closed by sdwheeler** 2020-09-14 12:10 UTC
Labels: about, core
