### ISSUE TITLE
"script" vs "statement" terminating errors

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/PowerShell-Docs#4682] opened 2019-08-23 16:11 UTC
Apparently there's 2 kind of terminating errors.  Like 1/0 is a "statement terminating error" and won't stop any pipeline or script, but will work with a try/catch.  https://github.com/MicrosoftDocs/PowerShell-Docs/issues/1583

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8071e91-ac2a-d032-eb9d-c22ff38aff3d
* Version Independent ID: dfeb5a94-3a03-2942-29aa-d3adfad742bc
* Content: [Terminating Errors](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/terminating-errors#feedback)
* Content Source: [developer/cmdlet/terminating-errors.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/developer/cmdlet/terminating-errors.md)
* Product: **powershell**
* Technology: **powershell-developer**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment] 2019-08-23 18:19
Duplicate of #1583

**Closed by sdwheeler** 2019-08-23 18:19 UTC
Labels: Area-SDK, Status-Duplicate
