### ISSUE TITLE
Unable to registrer nuget package provider in a PowerShell Core 7 session

### ISSUE THREAD

**Issue by moanrose** [MicrosoftDocs/PowerShell-Docs#6905] opened 2020-11-16 07:21 UTC
The documentation for this command seems to be out of date

When trying to issue the following command in a PowerShell Core 7 session

Install-PackageProvider -Name NuGet -RequiredVersion 2.8.5.201 -Force

I get the following exception

Install-PackageProvider: No match was found for the specified search criteria for the provider 'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.

I have the PSGallery PSREsposistory registred

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a7ae161-bc17-6c0d-9a4c-4e6ee796e717
* Version Independent ID: 1ca59e2b-35f8-34c8-19ec-609bf8d11527
* Content: [Install-PackageProvider (PackageManagement) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-packageprovider?view=powershell-7.1)
* Content Source: [reference/7.1/PackageManagement/Install-PackageProvider.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/PackageManagement/Install-PackageProvider.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by doctordns** [comment] 2020-11-16 11:00
A) I can duplicate this  
B) What happened to Nuget?

I think the issue is a little deeper. If you Get-Package Provider in WIndows PowerShell, you see this:
```powershell
PS C:\foo> Find-PackageProvider

Name                           Version          Source           Summary
----                           -------          ------           -------
nuget                          2.8.5.208        https://onege... NuGet provider for the OneGet meta-package manager
psl                            1.0.0.210        https://onege... psl provider for the OneGet meta-package manager
chocolatey                     2.8.5.130        https://onege... ChocolateyPrototype provider for the OneGet meta-pa...
PowerShellGet                  2.2.5            PSGallery        PowerShell module with commands for discovering, in...
DockerMsftProvider             1.0.0.8          PSGallery        PowerShell module with commands for discovering, in...
ChocolateyGet                  2.0.0            PSGallery        Package Management (OneGet) provider that facilitat...
DockerProvider                 0.0.0.3          PSGallery        PowerShell module with commands for discovering, in...
ContainerImage                 0.6.4.0          PSGallery        This is a PackageManagement provider module which h...
GitLabProvider                 1.3.8            PSGallery        GitLab PackageManagement provider
NanoServerPackage              1.0.1.0          PSGallery        A PackageManagement provider to  Discover, Save and...
Chocolatier                    1.2.0            PSGallery        Package Management (OneGet) provider that facilitat...
DockerMsftProviderInsider      1.0.0.2          PSGallery        PowerShell module with commands for discovering, in...
GistProvider                   0.6              PSGallery        Gist-as-a-Package - PackageManagement  PowerShell P...
GitHubProvider                 0.5              PSGallery        GitHub-as-a-Package - PackageManagement PowerShell ...
0install                       2.18.2           PSGallery        OneGet Package Provider for Zero Install
TSDProvider                    0.2              PSGallery        PowerShell PackageManager provider to search & inst...
OfficeProvider                 1.0.0.1          PSGallery        OfficeProvider allows users to install Microsoft Of...
AppxGet                        0.1.0.1          PSGallery        Powershell Package Management (OneGet) Provider for...
MyAlbum                        0.1.2            PSGallery        MyAlbum provider discovers the photos in your remot...
WSAProvider                    1.0.0.4          PSGallery        Provider to Discover, Install and inventory windows...
ChocoOneGet                    0.4.0            PSGallery        OneGet provider for Chocolatey
Pacman-Provider                0.0.1            PSGallery        Pacman provider enables installation of pacman pack...
```
whereas in PowerSHell 7.1 RTW:
```powershell
PS C:\Foo> Find-PackageProvider

Name                           Version          Source           Summary
----                           -------          ------           -------
PowerShellGet                  2.2.5            PSGallery        PowerShell module with commands for discovering, inst…
ChocolateyGet                  2.0.0            PSGallery        Package Management (OneGet) provider that facilitates…
ContainerImage                 0.6.4.0          PSGallery        This is a PackageManagement provider module which hel…
NanoServerPackage              1.0.1.0          PSGallery        A PackageManagement provider to  Discover, Save and I…
Chocolatier                    1.2.0            PSGallery        Package Management (OneGet) provider that facilitates…
WinGet                         0.0.1            PSGallery        Package Management (OneGet) provider that facilitates…
```

Something is not quite right. Or, I am totally misunderstanding what package providers are doing in PowerShell 7

**Comment by sdwheeler** [comment] 2020-11-16 13:32
Duplicate of #6868 - This is a product issue that is being tracked in OneGet/oneget#496.

**Closed by sdwheeler** 2020-11-16 13:32 UTC
Labels: packagemanagement, product-feedback, resolved-external
