### ISSUE TITLE
Missing installation guides for Slackware Linux

### ISSUE THREAD

**Issue by Yousha** [MicrosoftDocs/PowerShell-Docs#6449] opened 2020-08-07 09:07 UTC
These docs missing installation guides for Slackware Linux.
_Note: PowerShell works fine on Slackware Linux._

---
#### Document Details

* ID: 37f30869-1dcc-9b77-ecf3-e0ce88bce104
* Version Independent ID: a6f4b56d-aa6c-b557-c0d2-1ff6888c24bd
* Content: [Installing PowerShell on Linux - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment] 2020-08-07 11:48
We haven't tested those. You need to file a distribution support request in the PowerShell repo.
[Distribution Support Request](https://github.com/PowerShell/PowerShell/issues/new?assignees=&labels=Distribution-Request&template=Distribution_Request.md&title=Distribution+Support+Request)

Duplicate of #6147

**Closed by sdwheeler** 2020-08-07 11:48 UTC
