### ISSUE TITLE
Document the member-access enumeration feature and standardize terminology

### ISSUE THREAD

**Issue by IISResetMe** [MicrosoftDocs/PowerShell-Docs#8437] opened 2021-12-19 03:20 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.

### Summary of the new document or enhancement

Since version 3.0, PowerShell supports [member enumeration](https://devblogs.microsoft.com/powershell/new-v3-language-features/#member-enumeration):

```
PS ~> class Container { [int]$Number; Print(){ Write-Host "The number is: $($this.Number)" } }
PS ~> $objects = 1..5 |ForEach-Object { [Container]@{ Number = $_ } }
PS ~> $objects.Number
1
2
3
4
5
PS ~> $objects.Print()
The number is: 1
The number is: 2
The number is: 3
The number is: 4
The number is: 5
```

The array object stored in `$objects` has neither `Number` nor `Print` members, but the language engine implicitly enumerates (and dispatches the call to) the items contained in the array, as if we had evaluated `$objects |ForEach-Object Number` or `$objects |ForEach-Object Print`. 

Unfortunately, this feature - arguably a core aspect of modern PowerShell's behavior - is only fleetingly documented. Beyond the link above, it seems only to be further mentioned and/or taxonomized in the ["What's New in Windows PowerShell 5.0" help article](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/whats-new/what-s-new-in-windows-powershell-50?view=powershell-7.2#~text:property%20enumeration) where the first aspect of the feature - enumerating and dereferencing property values - is described as "property enumeration". 

Since "member enumeration" and "property enumeration" is already used in public and in active use by the community (as anecdotal evidence: I frequently find myself describing and naming these behaviors as such in answers on sites like StackOverflow), it might make sense to clarify this verbiage in the official documentation.

I believe the [`about_Properties`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_properties?view=powershell-7.2#properties-of-scalar-objects-and-collections) and [`about_Methods`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_methods) help files would be optimal documents to update with more opinionated feature names and more expansive descriptions and examples :) 

Thanks to @mklement0 for help researching this.

### Proposed title

Multiple help files

### List of related articles to link to

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_properties?view=powershell-7.2#properties-of-scalar-objects-and-collections
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_methods

**Comment by zett42** [comment] 2022-02-04 23:01
There seems to be a recent addition of a member enumeration section to [about_Arrays](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arrays?view=powershell-7.2#member-enumeration). 

It could be argued whether this is the right place, because the feature isn't restricted to arrays. It even says so in the documentation (emphasis mine): 

> You can use member enumeration to get property values from all members of a **collection**.

In my opinion this feature would deserve its own documentation page. It would certainly improve its discoverability by search engines. The topics that relate to it (e. g. _about_Arrays_, _about_Properties_ and _about_Methods_) could link to it from their "see also" section, also improving discoverability.

**Comment by sdwheeler** [comment] 2022-03-01 18:17
For consistency, we do not want to call this behavior "member enumeration", but a feature of the PowerShell engine with using the member access(`.`) operator on a collection object.

Updates to docs coming soon.

**Comment by IISResetMe** [comment] 2022-03-02 17:02
@sdwheeler I'm confused by your previous comment - is the officially documented feature name now "a feature of the PowerShell engine with using the member access(.) operator on a collection object."? That would IMO be less than helpful :)

**Comment by michaeltlombardi** [comment] 2022-03-09 22:34
@IISResetMe the clarification is that when you type `$foo.Bar` you are using the [_member access operator_ (`.`)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.3#member-access-operator-) on the `$foo` object. 

#7746 introduced a note to [`about_Arrays`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arrays?view=powershell-7.3#member-enumeration) to clarify that the member access operator will, if the _collection object_ does not have the specified member, enumerate the items of the collection and access the specified member on each item.

> You can use member enumeration to get property values from all members of a collection. When you use the member access operator (`.`) with a member name on a collection object, such as an array, if the collection object does not have a member of that name, the items of the collection are enumerated and PowerShell looks for that member on each item. This applies to both property and method members.

The [Methods of Scalar objects and Collections](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_methods?view=powershell-7.3#methods-of-scalar-objects-and-collections) section of `about_Methods` conveys this information again as it pertains to methods but with different language:

> Beginning in PowerShell 3.0, PowerShell tries to prevent scripting errors that result from the differing methods of scalar objects and collections.
>
> If you submit a collection, but request a method that exists only on single ("scalar") objects, PowerShell invokes the method on every object in the collection.
>
> If the method exists on the individual objects and on the collection, only the collection's method is invoked.

The [Property values](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_properties?view=powershell-7.3#property-values) section of `about_Properties` uses incorrect terminology, calling the member access operator the _dot method_, which might be confused for _dot source_. Later in the document, the [Properties of scalar objects and collections](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_properties?view=powershell-7.3#properties-of-scalar-objects-and-collections) section uses similar terminology as in `about_Methods` to describe the behavior of the member access operator as it pertains to properties (snipped for brevity):

> Beginning in PowerShell 3.0, PowerShell tries to prevent scripting errors that result from the differing properties of scalar objects and collections.
>
> ... 
>
> When you submit a collection, but request a property that exists only on single ("scalar") objects, PowerShell returns the value of that property for every object in the collection.
>
> ...
>
> If a property exists on the individual objects and on the collection, only the collection's property is returned.

## Example scenarios

The following examples clarify the behavior of PowerShell when using the member access operator on objects.

### Using the member access operator on a scalar object

```powershell
$Scalar = 'a'
```

When you use the member access operator on a scalar object that has the member, the command returns the property value or method result for that object.

```powershell
$Scalar.Length
$Scalar.ToUpper()
```
```output
1

A
```

When you use the member access operator on a scalar object that does not have the member, the command returns `$null` if you specify a property or a `MethodNotFound` error if you specify a method.

```powershell
$Scalar.DoesNotExist
$null -eq $Scalar.DoesNotExist
$Scalar.DoesNotExist()
```
```output


True

Method invocation failed because [System.String] does not contain a method named 'DoesNotExist'.
At line:1 char:1
+ $Scalar.DoesNotExist()
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

### Using the member access operator on a collection object

```powershell
[System.Collections.Generic.List[string]]$Collection = @('a', 'b')
```

When you use the member access operator on a collection object that has the member, the command always returns the property value or method result for the collection object.

In these example commands, the specified members exist on the collection but not the items in it.

```powershell
$Collection.IsReadOnly
$Collection.Add('c')
$Collection
```
```output
False



a
b
c
```

In these example commands, the specified members exist on both the collection and the items in it. Compare the results of the commands using the member access operator on the collection to the results from using the member access operator on the collection items in `ForEach-Object`. On the collection, the commands return the property value or method result for the collection object and not the items in it.

```powershell
$Collection.Count
$Collection | ForEach-Object -Process { $_.Count }
$Collection.ToString()
$Collection | ForEach-Object -Process { $_.ToString() }
```
```output
3

1
1
1

System.Collections.Generic.List`1[System.String]

a
b
c
```

When you use the member access operator on a collection object that does not have the member but the items in it do, PowerShell enumerates the items in the collection and returns the property value or method result for each item.

```powershell
$Collection.Length # MemberType: Property
$Collection.ToUpper() # MemberType: Method
```
```output
1
1
1

A
B
C
```

When you use the member access operator on a collection object that does not have the member and neither do the items in it, the command returns `$null` if you specify a property or a `MethodNotFound` error if you specify a method.

```powershell
$Collection.DoesNotExist
$null -eq $Collection.DoesNotExist
$Collection.DoesNotExist()
```
```output


True

Method invocation failed because [System.String] does not contain a method named 'DoesNotExist'.
At line:1 char:1
+ $Collection.DoesNotExist()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

Note that because the collection object does not have the member, PowerShell enumerated the items in the collection; the **MethodNotFound** error specifies that **System.String** does not contain the method instead of **System.Collections.Generic.List**.

When you use the member access operator to access a method on a collection object that does not have the method and only some of the items in the collection have it, the command returns a `MethodNotFound` error for the first item in the collection that does not have the method. The command does not return any other values, even for items in the collection which have the method.

```powershell
@('a', 1, 'c').ToUpper()
```
```output
Method invocation failed because [System.Int32] does not contain a method named 'ToUpper'.
At line:1 char:1
+ @('a', 1, 'c').ToUpper()
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

When you use the member access operator to access a property on a collection object that does not have the property and only some of the items in the collection have it, the command returns the property value for each item in the collection that has the property.

```powershell
$SpecialString = 'b' | Add-Member -NotePropertyMembers @{ NotShared = 'Foo' } -PassThru
$SpecialInt = 1 | Add-Member -NotePropertyMembers @{ NotShared = 'Bar' } -PassThru
[System.Collections.Generic.List[object]]$MixedCollection = @( 'a', $SpecialString, $SpecialInt, 2)
$MixedCollection.NotShared
```
```output
Foo
Bar
```

## Behavior Summary Table

| Member Type | Target     | Exists on Target | Exists on Collection Item | Behavior                                                                                               |
|-------------|------------|------------------|---------------------------|--------------------------------------------------------------------------------------------------------|
| Property    | Scalar     | True             | -                         | Return property value on the scalar                                                                    |
| Property    | Scalar     | False            | -                         | Return `$null`                                                                                         |
| Method      | Scalar     | True             | -                         | Call method on the scalar                                                                              |
| Method      | Scalar     | False            | -                         | Return **MethodNotFound** error                                                                        |
| Property    | Collection | True             | Any                       | Return property value on the collection                                                                |
| Property    | Collection | False            | All                       | Enumerate collection, return property value for every enumerated item                                  |
| Property    | Collection | False            | None                      | Return $null                                                                                           |
| Property    | Collection | False            | Mixed                     | Enumerate collection, return property value for every enumerated item with the property                |
| Method      | Collection | True             | Any                       | Call method on the scalar                                                                              |
| Method      | Collection | False            | All                       | Enumerate collection, call method on every enumerated item                                             |
| Method      | Collection | False            | None                      | Enumerate collection, return **MethodNotFound** error for the first enumerated item without the method |
| Method      | Collection | False            | Mixed                     | Enumerate collection, return **MethodNotFound** error for the first enumerated item without the method |

## Suggestions

1. Both `about_Methods` and `about_properties` should be updated to use the correct terminology and refer to the member access operator instead of existing mixed terminology.
2. The "Methods of scalar objects and collections" section of `about_Methods` should explicitly state that using the member access operator will return a **MethodNotFound** error if the specified member does not exist on the collection _and_ does not exist in one or more of the items in that collection.
3. The [PowerShell Glossary]() should include the term member access operator.

### Optional Suggestions

1. The examples of member access operators in `about_Properties` and `about_Methods` _may_ be updated to include more expansive examples of the behavior.
2. The "Member access operator" section in `about_Operators` _may_ be updated to include examples of the behavior on collections.
3. It _may_ be useful to document the behavior of the member access operator on scalars and collections in a single document and refer to it from the others.
4. It _may_ be useful to place a version of the behavior summary table in the documentation.

**Comment by mklement0** [comment] 2022-03-10 02:49
@michaeltlombardi, kudos for a thorough summary of the behavior, which undoubtedly deserves to make its way into the appropriate places in the documentation.

As for _terminology_, which is what this issue is about:

* Using _member access operator_ consistently makes sense.

* Users not familiar with PowerShell will intuitively know how `.`, the member-access operator, functions _type-natively_.

* What they will _not_ expect is _its implicit extension to collections_, and is precisely this concept that deserves _its own, pithy name_, as now already present in `about_Arrays`

As always, the _specific name chosen_ - while important - is less important than _giving the feature a name at all_, so it can be documented as such and can be talked about by others.

As for the specific name:

_Member enumeration_ strikes me as reasonable, but an alternative that highlights its foundation in the member-access operator could be _member-access enumeration_.

**Comment by zett42** [comment] 2022-03-10 10:41
Agreeing with @mklement0 that a specific name for the _implicit extension of member access to collections_ is beneficial. "Member access" is just too general in my opinion.

There is already existing practice for using the term "member enumeration", which dates back to 2012, when it was [first used](https://devblogs.microsoft.com/powershell/new-v3-language-features/).  

There could possibly be a better term, but I suggest we stick with the current, widely used term to avoid further confusion.

**Comment by michaeltlombardi** [comment] 2022-03-10 16:30
@mklement0, thanks for the feedback and suggestion. Chatting things over with the team, I think:

1.  _Member-access enumeration_ is the accurate, explicit name for this convenience feature. It's not the _most_ accurate and explicit name, but it is (relatively) short, clear, and explicit. Any more explicity (e.g. "member-access automatic collection enumeration") is unwieldy for little gain in my opinion.
2. The term _member enumeration_, while used and originating in the 2012 blog post (thank you @zett42!), is inaccurate and misleading; the _members_ are not being enumerated, the _items in a collection_ are being enumerated for convenience when using the member access operator. Enumerating the _members_ of an object - that is, listing all available members for that object - is descriptive of the behavior of `Get-Member`.
3. In terms of terminology confusion, I suggest that the issue is that the prior terminology was itself a bug that leads to an ambiguous interpretation of the feature and its usage. Additionally (though not of high priority or impact, just worth noting), I believe that calling this feature "member enumeration" primes a reader who does not already know about enumeration as a mathematical or computer science concept to have misleading expectations about what enumeration itself is when they encounter it elsewhere. "Member enumeration" implies that the _members_ are being enumerated (because member is a noun describing a concrete object) whereas "member-access enumeration" more clearly refers to enumeration behavior of an operation.
4. This functionality deserves its own about topic which should be referenced from `about_Operators`, `about_Properties`, `about_Methods`, and `about_Arrays`.

That in mind, I'm going to edit the title for this issue to reflect this and assign it to myself. I'll then begin the work to draft the `about_Member_Access_Enumeration` and update the other topics to reference it.

I think that other references to this behavior might be out of scope for _this_ issue but any discovered inaccuracies will be treated as documentation bugs.

**Comment by mklement0** [comment] 2022-03-10 16:41
Thanks for the thoughtful feedback, @michaeltlombardi.

I agree that _member enumeration_ can falsely suggest `Get-Member`-like behavior, so I welcome _member-access enumeration_.

Re 3.: _member enumeration_ wasn't widely used (until very recently in `about_Arrays`), and I think the real problem wasn't one of terminology, but the lack of awareness of the underlying _concepts_, due to the absence of both focused documentation for it and the lack of a term - a new conceptual `about_Member_Access_Enumeration` topic should address both issues.

**Comment by mklement0** [comment] 2022-03-10 16:47
@zett42, only just saw your comment : I think that _member-access enumeration_ is still recognizable to those familiar with _member enumeration_ while being more descriptive and less ambiguous than the latter. 

(But I have a few hundred SO posts to update now....)

**Closed** 2022-03-16 22:57 UTC
Labels: doc-idea
