### ISSUE TITLE
The word "Module" ought to be hyperlinked when used in Import-Module

### ISSUE THREAD

**Issue by Cwilson-dataselfcom** [MicrosoftDocs/PowerShell-Docs#6971] opened 2020-12-03 11:52 UTC
The concept a "Module" in central and core to understanding Import-Module  but 
The word is never hyperlinked

ALSO:  It ought to be clarified if .ps1 files not in "Modules" can be imported by this command.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52fda2d7-8d64-210b-ee01-8bc6d15f8448
* Version Independent ID: ade5a7a7-929d-065a-f448-b6afe3750be2
* Content: [Import-Module (Microsoft.PowerShell.Core) - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/Import-Module.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment] 2020-12-03 12:19
Duplicate of #6970 - see the answer in that issue.

**Closed by sdwheeler** 2020-12-03 12:19 UTC
