### ISSUE TITLE
Which Version

### ISSUE THREAD

**Issue by beermattuk** [MicrosoftDocs/PowerShell-Docs#3783] opened 2019-02-28 09:41 UTC
These help files really need to state which version the command was available from.  I don't have get-clipboard, powershell 5.1 apparently has.  But at which version was it introduced?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d3094b1-e22c-e134-5ace-6fae00afe8e4
* Version Independent ID: 0efcc112-2660-68d4-30ea-b6c633baa2a2
* Content: [Set-Clipboard (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-clipboard?view=powershell-5.1#feedback)
* Content Source: [reference/5.1/Microsoft.PowerShell.Management/Set-Clipboard.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Set-Clipboard.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by bobbytreed** [comment] 2019-02-28 11:12
Closing this as a duplicate of #2270

**Closed by bobbytreed** 2019-02-28 11:12 UTC
Labels: Duplicate
