### ISSUE TITLE
Scoop and Chocolatey Install

### ISSUE THREAD

**Issue by Naomi010Sentzke** [MicrosoftDocs/PowerShell-Docs#5628] opened 2020-03-24 10:30 UTC
Homebrew is mentioned for OS X but not Scoop/Chocolatey for Windows even though this is a Microsoft product

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell on Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment] 2020-03-24 13:13
Duplicate of #4986
Microsoft does not create or publish Scoop or Chocolatey packages so we cannot support them. Brew installs the package that we publish.

**Closed by sdwheeler** 2020-03-24 13:13 UTC
Labels: Area-Setup, Status-Duplicate
