### ISSUE TITLE
Why does stream direction only work to the Success stream?

### ISSUE THREAD

**Issue by deadlydog** [MicrosoftDocs/PowerShell-Docs#5165] opened 2019-11-26 21:15 UTC
Playing around with PowerShell it seems that using `*>&1` to send all streams to the Success stream is acceptable, but `*>&6` to send all streams to the Information stream is not valid. Same with `2>&3` or any other stream redirection that is not directing to the Success stream (i.e. stream 1). Why is only stream redirection to the Success stream supported? Could you update the docs to include this information please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523ffe7f-9667-0e70-be87-59b4862e41eb
* Version Independent ID: 2d6a2602-4480-d4d2-d63d-739c4d93e4b1
* Content: [about_Redirection - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Redirection.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Redirection.md)
* Product: **powershell**
* Technology: **powershell-cmdlets**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment] 2019-11-26 22:18
@deadlydog This is by design, but we can add a note to the documentation.

**Comment by sdwheeler** [comment] 2019-12-04 19:54
Fixed in #5189

**Closed by sdwheeler** 2019-12-04 19:54 UTC
Labels: Area-Language
