### ISSUE TITLE
New QuoteFields parameter in ConvertTo-Csv and Export-Csv

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/PowerShell-Docs#4122] opened 2019-04-05 17:17 UTC
Issue Details
-----------------

https://github.com/PowerShell/PowerShell/pull/9132 add new QuoteFields parameter to ConvertTo-Csv and Export-Csv

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by bobbytreed** [comment] 2019-05-21 10:20
This is a duplicate of #3900

**Closed by bobbytreed** 2019-05-21 10:20 UTC
Labels: Area-Cmdlets-Archive, Duplicate
