### ISSUE TITLE
.NET Global Tool versus MSI install for vscode

### ISSUE THREAD

**Issue by valetechsolutions** [MicrosoftDocs/PowerShell-Docs#5491] opened 2020-02-28 00:24 UTC
Installing this as a .NET global tool is easy, but the default install location is %UserProfile%\.dotnet\tools but this is not available to the Select default shell function when using VSCode on Windows. Using the MSI and getting an install in C:\Program Files works much better with respect to VSCode. I also tried installing as a .NET tool using the --tool-path option to install to the MSI directory, but the pwsh.exe was still not available to the Select default shell function. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46356aae-d82e-63ce-63cf-fe10cd47d76d
* Version Independent ID: c5ccf493-dc82-bb65-830a-d5857048ce26
* Content: [Installing PowerShell Core on Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment] 2020-02-28 02:20
@TylerLeonhardt @rjmholt Isn't this is fixed in an upcoming build of the PowerShell extension?

**Comment by rjmholt** [comment] 2020-02-28 02:52
[Not yet](https://github.com/PowerShell/vscode-powershell/blob/88a332403c96c7b8958a05bd640f70494dbf32ae/src/platform.ts#L189). @adityapatwardhan what versions of the dotnet global tool are affected by the startup bug?

**Comment by rjmholt** [comment] 2020-02-28 22:17
> Isn't this is fixed in an upcoming build of the PowerShell extension?

The answer is now yes, the next one

**Comment by sdwheeler** [comment] 2020-03-05 16:55
Closing this issue since the problem is fixed in the next release.

**Closed by sdwheeler** 2020-03-05 16:55 UTC
Labels: Area-Setup, Area-VSCode
