### ISSUE TITLE
Download docs as PDF

### ISSUE THREAD

**Issue by shikharraje** [MicrosoftDocs/PowerShell-Docs#6647] opened 2020-09-17 22:24 UTC
I'm a linux user, trying to script on Windows using PowerShell for the first time. Is there any way to get these docs as an offline PDF for easier/on-the-go reading? Something like: https://docs.microsoft.com/en-us/dotnet/fundamentals/ which has a "Download PDF" link at the bottom of the contents, on the left?

Thank You

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbe6956d-5391-1174-d4de-ba0e251da152
* Version Independent ID: c71a824d-0d60-dcbd-e18d-9798966f37a8
* Content: [How to use the PowerShell documentation - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/how-to-use-docs?view=powershell-7)
* Content Source: [reference/docs-conceptual/how-to-use-docs.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/how-to-use-docs.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by shikharraje** [comment] 2020-09-17 22:25
@joeyaiello , if you could provide me the steps, I can try to do it from within MS. My alias inside MS is **sraje** . Please let me know!

**Comment by sdwheeler** [comment] 2020-09-17 22:32
The PDF feature is not supported for PowerShell reference content.
Duplicate of #6283

**Closed by sdwheeler** 2020-09-17 22:32 UTC
Labels: doc-provided, duplicate
