### ISSUE TITLE
Page is empty

### ISSUE THREAD

**Issue by kaymccormick** [MicrosoftDocs/PowerShell-Docs#5256] opened 2019-12-28 03:21 UTC
Only contains only biolerplate headings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cc197e-962f-5a4c-eb59-548963b9030f
* Version Independent ID: 93cceb4c-c80a-b1ac-59a1-0c71ecfc47a6
* Content: [Defining Common Configuration Features - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/format/defining-common-configuration-features?view=powershell-6#feedback)
* Content Source: [reference/docs-conceptual/developer/format/defining-common-configuration-features.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/format/defining-common-configuration-features.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment] 2020-03-20 16:49
Duplicate of #2884

**Closed by sdwheeler** 2020-03-20 16:49 UTC
Labels: Area-SDK-Docs, Status-Duplicate
