### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by juvtib** [MicrosoftDocs/PowerShell-Docs#5667] opened 2020-03-30 10:53 UTC
The help for this cmdlet is empty. I understand that PowerShellGet is part of the default install now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a066be8-4177-44bf-3d51-8e33d1b719f9
* Version Independent ID: 6efe90b2-8b8b-42e7-72e8-6ba1b0b8be09
* Content: [Get-CredsFromCredentialProvider (PowerShellGet)](https://docs.microsoft.com/en-us/powershell/module/powershellget/get-credsfromcredentialprovider?view=powershell-7&viewFallbackFrom=powershell-5.1)
* Content Source: [reference/7.0/PowerShellGet/Get-CredsFromCredentialProvider.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/PowerShellGet/Get-CredsFromCredentialProvider.md)
* Product: **powershell**
* GitHub Login: @edyoung
* Microsoft Alias: **edyoung**

**Comment by sdwheeler** [comment] 2020-03-30 14:15
Duplicate of #5383

**Closed by sdwheeler** 2020-03-30 14:15 UTC
Labels: Status-Duplicate

**Comment by sdwheeler** [comment] 2020-03-30 21:26
Note- I found out that this is an internal function that was not intended to be exported from the module. The help is being removed. It will not be exported in the next release of PowerShellGet.
