### ISSUE TITLE
Get-help -online results in error 404 for get-childitem and set-content, probably more

### ISSUE THREAD

**Issue by ejheeres** [MicrosoftDocs/PowerShell-Docs#4218] opened 2019-04-25 14:43 UTC
Describing the bug:
In Windows PowerShell, running Get-Help Get-ChildItem -Online opens https://docs.microsoft.com/en-us/powershell/module/4.0/microsoft.powershell.core/providers/FileSystem-Provider/Get-ChildItem-for-Filesystem (404). Also running get-help set-content -online results in the same 404 error, the url this time is : https://docs.microsoft.com/nl-nl/powershell/module/4.0/microsoft.powershell.core/providers/FileSystem-Provider/Set-Content-for-Filesystem

If I manually change the url to https://docs.microsoft.com/nl-nl/powershell/module/Microsoft.PowerShell.Management/Set-Content?view=powershell-5.0 then it seems to be working fine. 

The same goes for the get-childitem cmdlet, when changing the URL to https://docs.microsoft.com/nl-nl/powershell/module/Microsoft.PowerShell.Management/Get-Childitem?view=powershell-5.0 I can see the help.

Update-module does not work because the microsoft.powershell.management was not installed through install-module.

To reproduce

Open PowerShell
Run Get-Help -Get-ChildItem -Online
Run Get-help Set-content -online

Both of them result in error 404.

OS: Windows 10
Browser: Microsoft Edge, Google Chrome
It does not seem to be browser dependent.
Powershell core does NOT seem to have this problem, they point to another url. It's only Windows Powershell from what I can see.

**Comment by sdwheeler** [comment] 2019-04-25 16:39
@ejheeres What version of PowerShell are you using? It looks like you are using v4?

**Comment by ejheeres** [comment] 2019-04-25 16:46
> @ejheeres What version of PowerShell are you using? It looks like you are using v4?

I am using Windows Powershell version 5.1. Below are the contents of $psversiontable
Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by sdwheeler** [comment] 2019-04-25 17:20
OK, this is a known issue with the Updateable Help. The links have been fixed in the markdown source but the help is broken because our pipeline to publish updates to Updateable Help is broken for PowerShell 5.1 and older.

**Comment by ejheeres** [comment] 2019-05-03 11:18
I've been doing some more research and it seems that people who have not updated their modules recently are still able to use the cmdlet and they will be able to see the online help topic just fine. So I asked some of them to run "get-help get-childitem -online -verbose" to see what url they were opening. 
The ones where it was working all resolved "http://go.microsoft.com/fwlink/?LinkID=113308". However, the ones were it did not work were resolving this url: "http://technet.microsoft.com/library/hh847897(v=wps.630).aspx"

Now with the last part comes something I have not yet found out, when I look at the HelpUri property of the cmdlet on my machine where it does not work, it sais http://go.microsoft.com/fwlink/?LinkID=113308, but when opening it seems to ignore that and instead tries to open http://technet.microsoft.com/library/hh847897(v=wps.630).aspx 

I'm not sure if this is an issue with cmdlet get-childitem or with get-help itself which for some reason perhaps uses a wrong url.

**Comment by sdwheeler** [comment] 2020-03-20 16:07
Duplicate of #2298

**Closed by sdwheeler** 2020-03-20 16:07 UTC
Labels: Area-HelpSystem
